<#
.SYNOPSIS
    Sample start-up profile

.DESCRIPTION
    This sample is intented to be copied on top of the standard MS profile.

    cp sample-profile.ps1 $PROFILE

    Be sure to look at the original profile to make certain you aren't killing anything.
    You might also consier:

    cp $PROFILE ~\.mysetup\old-profile.ps1
    code sample-profile.ps1 (edit profile to call this file), then
    cp sample-profile.ps1 $PROFILE

.PARAMETER (none)
    None

.INPUTS
    No inputs required

.OUTPUTS
    No outputs

.NOTES
    Author: John Leonard
    Date: 8/14/2023
    Version: 1.0

    Added new QUARTO section
    Date: 11/3/2023
    Version: 1.1

.LINK
    None

#>

write-output "Running profile: $PROFILE"

$ENV:PATH="$ENV:PATH;$ENV:APPDATA\Python\Scripts"
$ENV:PATH="$ENV:PATH;C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn"

## Aliases added on 10/29/2023 by JL
## The powershell SET-ALIAS function doesn't accept arguments, so we'll use function instead
function ListPath {$env:PATH -split ";"}
function ListEnv {Get-ChildItem Env: | Sort-Object Name | Format-Table Name, Value -AutoSize}


# These settings disable annoying quarto messages
$env:DENO_NO_UPDATE_CHECK=1               # to warning about deno upgrades
$env:DENO_TLS_CA_STORE="system"           # to stop the BAD CERTIFICATE deno warning
$env:PYDEVD_DISABLE_FILE_VALIDATION=1     # for Python 3.11 above, to disable warning message RE: debugging
$env:VIRTUAL_ENV_DISABLE_PROMPT=1         # set to 1 to disable venv prompt change

# This code ensures Quarto finds the correct python from pyenv or poetry if a venv exists.
$env:QUARTO_PYTHON=$(pyenv which python)  # to work with pyenv global or local python
$pythonPoetryPath = $(poetry env info -e 2> $null)
if ($pythonPoetryPath -ne $null) {
  # extract the venv name from the python poetry path
  $venvName = Split-Path -Path $pythonPoetryPath -Parent | Split-Path -Parent | Split-Path -Leaf
  Write-Output "QUARTO_PYTHON set to Poetry venv: $venvName"
  $env:QUARTO_PYTHON=$var                 # override with poetry venv python as needed
} else {
  Write-Output "QUARTO_PYTHON set to $(pyenv version)"
}

# posh prompt shows current venv, so disable the prompt change above!
oh-my-posh init pwsh --config=$env:USERPROFILE\.mysetup\jleonard99.omp.json| invoke-expression

# SIG # Begin signature block
# MIIcjwYJKoZIhvcNAQcCoIIcgDCCHHwCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCBO9cMykEX8W6Ei
# ppfWEhpVdJwyU5geeegrQkrh5/VTWaCCC3owggW4MIIEoKADAgECAhN3AANz9uJH
# VnJLsSYVAAAAA3P2MA0GCSqGSIb3DQEBCwUAMHExEzARBgoJkiaJk/IsZAEZFgNl
# ZHUxEzARBgoJkiaJk/IsZAEZFgN2Y3UxEzARBgoJkiaJk/IsZAEZFgNhZHAxFDAS
# BgoJkiaJk/IsZAEZFgRSQU1TMRowGAYDVQQDExFWQ1UgSW5mb1NlYyBTdWJDQTAe
# Fw0yMzA4MjMxNzM3MDNaFw0yNDA4MjIxNzM3MDNaMIGtMRMwEQYKCZImiZPyLGQB
# GRYDZWR1MRMwEQYKCZImiZPyLGQBGRYDdmN1MRMwEQYKCZImiZPyLGQBGRYDYWRw
# MRQwEgYKCZImiZPyLGQBGRYEUkFNUzEeMBwGA1UECxMVU2Nob29sIG9mIEVuZ2lu
# ZWVyaW5nMQ4wDAYDVQQLEwVVc2VyczESMBAGA1UECxMJRW1wbG95ZWVzMRIwEAYD
# VQQDEwlqZGxlb25hcmQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC4
# 09gf/tyK9r6xKYP2nlmgnDaHe7PotZfuVPoaBTsvHfdiDoeE7bxJk8N/59aQdYbt
# Ev0oohRbl0RH/0vMua3soEazK7FyUorquFI6VcTxrCP9g+/UWzPrJoGv7uGG8IRq
# R6YoBoTSSHAiBfRqxI7udHypP5WAQcBwq7Hn7oKa++lWZM9+wfNjqpaAx8hPf5Uj
# RjwbcJebvsQPmY7GCFQUELjyTFkF/1TOMRtwdeyhQcdFkEFkcoruWNfiW8XEopP3
# C9skBetSZFik6oExa42k5LV7kMUoElVvMb1iFWVxchBsH1w1X4/tcoeTMeTxlppp
# SgywX6QbOYuwfuDSit5RAgMBAAGjggIKMIICBjA+BgkrBgEEAYI3FQcEMTAvBicr
# BgEEAYI3FQiFjq5yhJy9CYfRiySFqbpLgojRSIF5g76Ib4WwiwECAWQCAQUwEwYD
# VR0lBAwwCgYIKwYBBQUHAwMwDgYDVR0PAQH/BAQDAgeAMBsGCSsGAQQBgjcVCgQO
# MAwwCgYIKwYBBQUHAwMwHQYDVR0OBBYEFHof0pBD1o9KBQMYrZLkK8dlGa2HMB8G
# A1UdIwQYMBaAFBU9I1n1ZMI0JksZb0Pw845V3DIhMEgGA1UdHwRBMD8wPaA7oDmG
# N2h0dHA6Ly9wa2kudmN1LmVkdS9DZXJ0RW5yb2xsL1ZDVSUyMEluZm9TZWMlMjBT
# dWJDQS5jcmwweAYIKwYBBQUHAQEEbDBqMEMGCCsGAQUFBzAChjdodHRwOi8vcGtp
# LnZjdS5lZHUvQ2VydEVucm9sbC9WQ1UlMjBJbmZvU2VjJTIwU3ViQ0EuY3J0MCMG
# CCsGAQUFBzABhhdodHRwOi8vcGtpLnZjdS5lZHUvb2NzcDAsBgNVHREEJTAjoCEG
# CisGAQQBgjcUAgOgEwwRamRsZW9uYXJkQHZjdS5lZHUwUAYJKwYBBAGCNxkCBEMw
# QaA/BgorBgEEAYI3GQIBoDEEL1MtMS01LTIxLTMzNjIxMzQ2NzQtMTQzNDI1NDg3
# MC02MTg0MjQwMTgtMTQyMTE5MA0GCSqGSIb3DQEBCwUAA4IBAQCsvQ9KiQmqjLhR
# C8SU2cnTo6jfkF2sv6Y4dNvClRproJusFmB+m8sJbVBGfibgQ7HD6KOjDfxp9p+y
# GfYZ6ob3fICAOmyo37qrmYTm3HQSMSiVpvOUYj2ckHKpcvN/jZwZ0ottZRzj461J
# 4XURToOpiVK3aoNfnXT6Au6DxAZARNO4S0oWtqLzkiyYKPJLKq0oNS2IV+WRBnit
# olKK16pl9/Jk2Eb93TkzffqFa/Yjs7tHQOkweaMAZ5rbKhOMFmgTWIktXS8s5Vd0
# QfWNOQih8NtSbnYuQA0ANyrl01DW94XMeWI3rS+/xHiyC9VKsMaeE69LWlyYeTH/
# L4oHthdzMIIFujCCA6KgAwIBAgITHwAAAAbNiK9rbBvq+AAAAAAABjANBgkqhkiG
# 9w0BAQ0FADAWMRQwEgYDVQQDEwtWQ1UgUm9vdCBDQTAeFw0xNzA5MTMxNjI0NTVa
# Fw0yNzA5MTMxNjM0NTVaMHExEzARBgoJkiaJk/IsZAEZFgNlZHUxEzARBgoJkiaJ
# k/IsZAEZFgN2Y3UxEzARBgoJkiaJk/IsZAEZFgNhZHAxFDASBgoJkiaJk/IsZAEZ
# FgRSQU1TMRowGAYDVQQDExFWQ1UgSW5mb1NlYyBTdWJDQTCCASIwDQYJKoZIhvcN
# AQEBBQADggEPADCCAQoCggEBAMBzjWLmzh8TmxKSY0548f4FwBnBd5s5l3Vkbv7E
# ob+7aFXxgAC23XLAOhtUeGiISjkhpu0R/2paZbhJ3ezOzcKQ7n3bJw4GYbZDrfEy
# MvCg2wSivZ0UvpxUv2h5n7tR/i/bdkxEk3/jYja1N9X/U24s5fqdlkjPUJJ1hmSh
# Ni1epz/afOFDI+hXiKIpwaE1JaooJhghcKkh700Z9hT4vKQ4rmiApb7O3/iNczbj
# +B1wkeLnecGt/GGUdUPRW11q4/Amjfz7v0lxq6iAgnpHi3ntBWu2zsy3cGCHsEDp
# EvBUJCpqma/zbI8scKS+MQuy8wj5sjRjioQwzi49Kqahz3MCAwEAAaOCAaQwggGg
# MBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBQVPSNZ9WTCNCZLGW9D8POOVdwy
# ITB6BgNVHSAEczBxMG8GBysGAQQB0RAwZDA6BggrBgEFBQcCAjAuHiwATABlAGcA
# YQBsACAAUABvAGwAaQBjAHkAIABTAHQAYQB0AGUAbQBlAG4AdDAmBggrBgEFBQcC
# ARYaaHR0cDovL3BraS52Y3UuZWR1L2Nwcy50eHQwGQYJKwYBBAGCNxQCBAweCgBT
# AHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0jBBgw
# FoAUk4PNShVEeUceCSFYZPM8uEbc71owQgYDVR0fBDswOTA3oDWgM4YxaHR0cDov
# L3BraS52Y3UuZWR1L2NlcnRlbnJvbGwvVkNVJTIwUm9vdCUyMENBLmNybDBTBggr
# BgEFBQcBAQRHMEUwQwYIKwYBBQUHMAKGN2h0dHA6Ly9wa2kudmN1LmVkdS9DZXJ0
# RW5yb2xsL0FMQlVTX1ZDVSUyMFJvb3QlMjBDQS5jcnQwDQYJKoZIhvcNAQENBQAD
# ggIBAFoSJfRjPLt2/AjScl1g0Oe9KYoYaVcJEe43buGEfGT1UE7wnN2wTztZibl8
# mO4f2elo+O1fM+3Hl9ESlQOsVW2pVrIUQ+ZW1CJ+bRVflLh9Pi6vSu+6gguNAZFp
# 1W5czWli5jPJTXVPbP5Hz30BmnrBdUKlL/fQkMhGmOhZpfC1bUTd6gGALU1/GmfB
# 1vwU+KAU4dWHiCEQWDvVnGcYsZfPmJpAtr4t6XLFrFeYuqCr8MNHlmm5C+1AxxlP
# aSiQRp3lQJaoQthLAU/SJ6Xqobp+cvxYOkkMUL9zvbZ58wQcTwekVIAH8FQlv1Fj
# BkxK0TGnwkbXWrfGSVAnGBtxPkmtfQm25zeyhQOzjZSNOHJUIvUrWZlIvQaItsd3
# ooO2yJh1XmuR7UY2QkwHvcie62IXIe66vwASHpMM57lnykxrDpxXAalBx5vU3hj9
# NOj1u6Wh6GxIFzLnmtqTc/scZLWuzQe1T84WlDRI7gu9KcRO2SLm+ncBMg7nbeJh
# lq4i1WwzwKvN6zGBaHkApd8ctGV0l1lNAqycaO87S3PZxzxTB/UwwbJcUPvWRC+B
# DdKSxJ1aHyXHs0Ce3s0vydH1PeG53Cdog9BCEluOFsIceNf9OPMTMaHYXvzzH37n
# k4UAeguS5mDv6sqmzI2ohVbIK1f4cnFzM5Z51varyy2ettzXMYIQazCCEGcCAQEw
# gYgwcTETMBEGCgmSJomT8ixkARkWA2VkdTETMBEGCgmSJomT8ixkARkWA3ZjdTET
# MBEGCgmSJomT8ixkARkWA2FkcDEUMBIGCgmSJomT8ixkARkWBFJBTVMxGjAYBgNV
# BAMTEVZDVSBJbmZvU2VjIFN1YkNBAhN3AANz9uJHVnJLsSYVAAAAA3P2MA0GCWCG
# SAFlAwQCAQUAoIGEMBgGCisGAQQBgjcCAQwxCjAIoAKAAKECgAAwGQYJKoZIhvcN
# AQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUw
# LwYJKoZIhvcNAQkEMSIEIG6fdZXwoS9mUns1s/rLEW8/Cg5INTComkBMhVptYoL0
# MA0GCSqGSIb3DQEBAQUABIIBAC4RMmFthyXBCkabRRprwxnNABEqo0L1WRolwWf+
# cCwmvdxiCqt3v3rJVBy6gIe/cJTtAWv9V0qP6eIFeyILFAg3dZgIa5aEUwCxiEJG
# mTm2J5pnkqOfyZtu8S2DkYqMSnS3DOrGscJfCIvAeLqW2lFaoH/71xvuo2nYHe3n
# lKEO8r1MapnPrJtXgwYT5UCrvIjhbSBwSCXptSr1WfrPkfwuoSUGX7Ztug0YGQdt
# 9OnjZE8RUlrhtpk/jfZHG0qfRlnwDpuQWrvpgomeKRAVTJWIvKgoygNw50w44mbL
# A3/E2Ij6xGHDr0HCIwClFrO5ejigWUF/Cp5h3g51dvpUEQ2hgg4sMIIOKAYKKwYB
# BAGCNwMDATGCDhgwgg4UBgkqhkiG9w0BBwKggg4FMIIOAQIBAzENMAsGCWCGSAFl
# AwQCATCB/wYLKoZIhvcNAQkQAQSgge8EgewwgekCAQEGC2CGSAGG+EUBBxcDMCEw
# CQYFKw4DAhoFAAQU0Z5ZEeP/k5WmVWB2hEQMSA75RaECFQC383m28qleU6YDUziN
# JOy7+425ehgPMjAyMzExMDMxMTMzMjdaMAMCAR6ggYakgYMwgYAxCzAJBgNVBAYT
# AlVTMR0wGwYDVQQKExRTeW1hbnRlYyBDb3Jwb3JhdGlvbjEfMB0GA1UECxMWU3lt
# YW50ZWMgVHJ1c3QgTmV0d29yazExMC8GA1UEAxMoU3ltYW50ZWMgU0hBMjU2IFRp
# bWVTdGFtcGluZyBTaWduZXIgLSBHM6CCCoswggU4MIIEIKADAgECAhB7BbHUSWhR
# RPfJidKcGZ0SMA0GCSqGSIb3DQEBCwUAMIG9MQswCQYDVQQGEwJVUzEXMBUGA1UE
# ChMOVmVyaVNpZ24sIEluYy4xHzAdBgNVBAsTFlZlcmlTaWduIFRydXN0IE5ldHdv
# cmsxOjA4BgNVBAsTMShjKSAyMDA4IFZlcmlTaWduLCBJbmMuIC0gRm9yIGF1dGhv
# cml6ZWQgdXNlIG9ubHkxODA2BgNVBAMTL1ZlcmlTaWduIFVuaXZlcnNhbCBSb290
# IENlcnRpZmljYXRpb24gQXV0aG9yaXR5MB4XDTE2MDExMjAwMDAwMFoXDTMxMDEx
# MTIzNTk1OVowdzELMAkGA1UEBhMCVVMxHTAbBgNVBAoTFFN5bWFudGVjIENvcnBv
# cmF0aW9uMR8wHQYDVQQLExZTeW1hbnRlYyBUcnVzdCBOZXR3b3JrMSgwJgYDVQQD
# Ex9TeW1hbnRlYyBTSEEyNTYgVGltZVN0YW1waW5nIENBMIIBIjANBgkqhkiG9w0B
# AQEFAAOCAQ8AMIIBCgKCAQEAu1mdWVVPnYxyXRqBoutV87ABrTxxrDKPBWuGmicA
# MpdqTclkFEspu8LZKbku7GOz4c8/C1aQ+GIbfuumB+Lef15tQDjUkQbnQXx5HMvL
# rRu/2JWR8/DubPitljkuf8EnuHg5xYSl7e2vh47Ojcdt6tKYtTofHjmdw/SaqPSE
# 4cTRfHHGBim0P+SDDSbDewg+TfkKtzNJ/8o71PWym0vhiJka9cDpMxTW38eA25Hu
# /rySV3J39M2ozP4J9ZM3vpWIasXc9LFL1M7oCZFftYR5NYp4rBkyjyPBMkEbWQ6p
# PrHM+dYr77fY5NUdbRE6kvaTyZzjSO67Uw7UNpeGeMWhNwIDAQABo4IBdzCCAXMw
# DgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQAwZgYDVR0gBF8wXTBb
# BgtghkgBhvhFAQcXAzBMMCMGCCsGAQUFBwIBFhdodHRwczovL2Quc3ltY2IuY29t
# L2NwczAlBggrBgEFBQcCAjAZGhdodHRwczovL2Quc3ltY2IuY29tL3JwYTAuBggr
# BgEFBQcBAQQiMCAwHgYIKwYBBQUHMAGGEmh0dHA6Ly9zLnN5bWNkLmNvbTA2BgNV
# HR8ELzAtMCugKaAnhiVodHRwOi8vcy5zeW1jYi5jb20vdW5pdmVyc2FsLXJvb3Qu
# Y3JsMBMGA1UdJQQMMAoGCCsGAQUFBwMIMCgGA1UdEQQhMB+kHTAbMRkwFwYDVQQD
# ExBUaW1lU3RhbXAtMjA0OC0zMB0GA1UdDgQWBBSvY9bKo06FcuCnvEHzKaI4f4B1
# YjAfBgNVHSMEGDAWgBS2d/ppSEefUxLVwuoHMnYH0ZcHGTANBgkqhkiG9w0BAQsF
# AAOCAQEAdeqwLdU0GVwyRf4O4dRPpnjBb9fq3dxP86HIgYj3p48V5kApreZd9KLZ
# VmSEcTAq3R5hF2YgVgaYGY1dcfL4l7wJ/RyRR8ni6I0D+8yQL9YKbE4z7Na0k8hM
# kGNIOUAhxN3WbomYPLWYl+ipBrcJyY9TV0GQL+EeTU7cyhB4bEJu8LbF+GFcUvVO
# 9muN90p6vvPN/QPX2fYDqA/jU/cKdezGdS6qZoUEmbf4Blfhxg726K/a7JsYH6q5
# 4zoAv86KlMsB257HOLsPUqvR45QDYApNoP4nbRQy/D+XQOG/mYnb5DkUvdrk08Pq
# K1qzlVhVBH3HmuwjA42FKtL/rqlhgTCCBUswggQzoAMCAQICEHvU5a+6zAc/oQEj
# BCJBTRIwDQYJKoZIhvcNAQELBQAwdzELMAkGA1UEBhMCVVMxHTAbBgNVBAoTFFN5
# bWFudGVjIENvcnBvcmF0aW9uMR8wHQYDVQQLExZTeW1hbnRlYyBUcnVzdCBOZXR3
# b3JrMSgwJgYDVQQDEx9TeW1hbnRlYyBTSEEyNTYgVGltZVN0YW1waW5nIENBMB4X
# DTE3MTIyMzAwMDAwMFoXDTI5MDMyMjIzNTk1OVowgYAxCzAJBgNVBAYTAlVTMR0w
# GwYDVQQKExRTeW1hbnRlYyBDb3Jwb3JhdGlvbjEfMB0GA1UECxMWU3ltYW50ZWMg
# VHJ1c3QgTmV0d29yazExMC8GA1UEAxMoU3ltYW50ZWMgU0hBMjU2IFRpbWVTdGFt
# cGluZyBTaWduZXIgLSBHMzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
# AK8Oiqr43L9pe1QXcUcJvY08gfh0FXdnkJz93k4Cnkt29uU2PmXVJCBtMPndHYPp
# PydKM05tForkjUCNIqq+pwsb0ge2PLUaJCj4G3JRPcgJiCYIOvn6QyN1R3AMs19b
# jwgdckhXZU2vAjxA9/TdMjiTP+UspvNZI8uA3hNN+RDJqgoYbFVhV9HxAizEtavy
# bCPSnw0PGWythWJp/U6FwYpSMatb2Ml0UuNXbCK/VX9vygarP0q3InZl7Ow28paV
# gSYs/buYqgE4068lQJsJU/ApV4VYXuqFSEEhh+XetNMmsntAU1h5jlIxBk2UA0XE
# zjwD7LcA8joixbRv5e+wipsCAwEAAaOCAccwggHDMAwGA1UdEwEB/wQCMAAwZgYD
# VR0gBF8wXTBbBgtghkgBhvhFAQcXAzBMMCMGCCsGAQUFBwIBFhdodHRwczovL2Qu
# c3ltY2IuY29tL2NwczAlBggrBgEFBQcCAjAZGhdodHRwczovL2Quc3ltY2IuY29t
# L3JwYTBABgNVHR8EOTA3MDWgM6Axhi9odHRwOi8vdHMtY3JsLndzLnN5bWFudGVj
# LmNvbS9zaGEyNTYtdHNzLWNhLmNybDAWBgNVHSUBAf8EDDAKBggrBgEFBQcDCDAO
# BgNVHQ8BAf8EBAMCB4AwdwYIKwYBBQUHAQEEazBpMCoGCCsGAQUFBzABhh5odHRw
# Oi8vdHMtb2NzcC53cy5zeW1hbnRlYy5jb20wOwYIKwYBBQUHMAKGL2h0dHA6Ly90
# cy1haWEud3Muc3ltYW50ZWMuY29tL3NoYTI1Ni10c3MtY2EuY2VyMCgGA1UdEQQh
# MB+kHTAbMRkwFwYDVQQDExBUaW1lU3RhbXAtMjA0OC02MB0GA1UdDgQWBBSlEwGp
# n4XMG24WHl87Map5NgB7HTAfBgNVHSMEGDAWgBSvY9bKo06FcuCnvEHzKaI4f4B1
# YjANBgkqhkiG9w0BAQsFAAOCAQEARp6v8LiiX6KZSM+oJ0shzbK5pnJwYy/jVSl7
# OUZO535lBliLvFeKkg0I2BC6NiT6Cnv7O9Niv0qUFeaC24pUbf8o/mfPcT/mMwnZ
# olkQ9B5K/mXM3tRr41IpdQBKK6XMy5voqU33tBdZkkHDtz+G5vbAf0Q8RlwXWuOk
# O9VpJtUhfeGAZ35irLdOLhWa5Zwjr1sR6nGpQfkNeTipoQ3PtLHaPpp6xyLFdM3f
# RwmGxPyRJbIblumFCOjd6nRgbmClVnoNyERY3Ob5SBSe5b/eAL13sZgUchQk38cR
# LB8AP8NLFMZnHMweBqOQX1xUiz7jM1uCD8W3hgJOcZ/pZkU/djGCAlowggJWAgEB
# MIGLMHcxCzAJBgNVBAYTAlVTMR0wGwYDVQQKExRTeW1hbnRlYyBDb3Jwb3JhdGlv
# bjEfMB0GA1UECxMWU3ltYW50ZWMgVHJ1c3QgTmV0d29yazEoMCYGA1UEAxMfU3lt
# YW50ZWMgU0hBMjU2IFRpbWVTdGFtcGluZyBDQQIQe9Tlr7rMBz+hASMEIkFNEjAL
# BglghkgBZQMEAgGggaQwGgYJKoZIhvcNAQkDMQ0GCyqGSIb3DQEJEAEEMBwGCSqG
# SIb3DQEJBTEPFw0yMzExMDMxMTMzMjdaMC8GCSqGSIb3DQEJBDEiBCDX3YABeyUU
# MHRqgCHkFs4jx7LpKADBQ+Jr0hcl6sK7GzA3BgsqhkiG9w0BCRACLzEoMCYwJDAi
# BCDEdM52AH0COU4NpeTefBTGgPniggE8/vZT7123H99h+DALBgkqhkiG9w0BAQEE
# ggEARDcJBxwPUzl2kWtFM7snTI4ooiIPdqLhlafzJU3+mmq6luGq/HxKUk1bS0Vl
# lgrPxZ1RmHv0EDNvXxTpg4i9ku5x+0Xsda/D5aH3Kc6NLv8xTZnXpILyM53vsQwP
# GO6TizP2aCzZHOPpaK1qOPqdY7rCskfqXuff9WL0Tkg9HIxtB8Kff9+zQBISu5g0
# 54RrzV20tIudSvuqPzDW4eyOWAFGG6WDwgQMPKzHFzgfR9hB83/xx4x0uKdgj0v/
# QMT2Z38kZ8yDFLV8L0RA0ScNqV5+MJQBvwpbbXowvluEJZUKZnDtH7Rxx4qa33Sa
# hQm9J9p+tabSh4wwrlYj6cN+kA==
# SIG # End signature block
