Function Set-WallPaper {
<#
 
    .SYNOPSIS
    Applies a specified wallpaper to the current user's desktop
    
    .PARAMETER Image
    Provide the exact path to the image
 
    .PARAMETER Style
    Provide wallpaper style (Example: Fill, Fit, Stretch, Tile, Center, or Span)
  
    .EXAMPLE
    Set-WallPaper -Image "C:\Wallpaper\Default.jpg"
    Set-WallPaper -Image "C:\Wallpaper\Background.jpg" -Style Fit
  
#>
 
param (
    [parameter(Mandatory=$True)]
    # Provide path to image
    [string]$Image,
    # Provide wallpaper style that you would like applied
    [parameter(Mandatory=$False)]
    [ValidateSet('Fill', 'Fit', 'Stretch', 'Tile', 'Center', 'Span')]
    [string]$Style
)
 
$WallpaperStyle = Switch ($Style) {
  
    "Fill" {"10"}
    "Fit" {"6"}
    "Stretch" {"2"}
    "Tile" {"0"}
    "Center" {"0"}
    "Span" {"22"}
  
}
 
If($Style -eq "Tile") {
 
    New-ItemProperty -Path "HKCU:\Control Panel\Desktop" -Name WallpaperStyle -PropertyType String -Value $WallpaperStyle -Force
    New-ItemProperty -Path "HKCU:\Control Panel\Desktop" -Name TileWallpaper -PropertyType String -Value 1 -Force
 
}
Else {
 
    New-ItemProperty -Path "HKCU:\Control Panel\Desktop" -Name WallpaperStyle -PropertyType String -Value $WallpaperStyle -Force
    New-ItemProperty -Path "HKCU:\Control Panel\Desktop" -Name TileWallpaper -PropertyType String -Value 0 -Force
 
}
 
Add-Type -TypeDefinition @" 
using System; 
using System.Runtime.InteropServices;
  
public class Params
{ 
    [DllImport("User32.dll",CharSet=CharSet.Unicode)] 
    public static extern int SystemParametersInfo (Int32 uAction, 
                                                   Int32 uParam, 
                                                   String lpvParam, 
                                                   Int32 fuWinIni);
}
"@ 
  
    $SPI_SETDESKWALLPAPER = 0x0014
    $UpdateIniFile = 0x01
    $SendChangeEvent = 0x02
  
    $fWinIni = $UpdateIniFile -bor $SendChangeEvent
  
    $ret = [Params]::SystemParametersInfo($SPI_SETDESKWALLPAPER, 0, $Image, $fWinIni)
}
 
Set-WallPaper -Image "$env:USERPROFILE\.my-setup\backgroundDefault.jpg" -Style Fit


# SIG # Begin signature block
# MIIcaQYJKoZIhvcNAQcCoIIcWjCCHFYCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQU7UkiFDVxLBjNJYsdZc0Bdtyp
# ceGgggt6MIIFuDCCBKCgAwIBAgITdwADHyGEzSvvnOHjlQAAAAMfITANBgkqhkiG
# 9w0BAQsFADBxMRMwEQYKCZImiZPyLGQBGRYDZWR1MRMwEQYKCZImiZPyLGQBGRYD
# dmN1MRMwEQYKCZImiZPyLGQBGRYDYWRwMRQwEgYKCZImiZPyLGQBGRYEUkFNUzEa
# MBgGA1UEAxMRVkNVIEluZm9TZWMgU3ViQ0EwHhcNMjIxMjE0MTI1NDA1WhcNMjMx
# MjE0MTI1NDA1WjCBrTETMBEGCgmSJomT8ixkARkWA2VkdTETMBEGCgmSJomT8ixk
# ARkWA3ZjdTETMBEGCgmSJomT8ixkARkWA2FkcDEUMBIGCgmSJomT8ixkARkWBFJB
# TVMxHjAcBgNVBAsTFVNjaG9vbCBvZiBFbmdpbmVlcmluZzEOMAwGA1UECxMFVXNl
# cnMxEjAQBgNVBAsTCUVtcGxveWVlczESMBAGA1UEAxMJamRsZW9uYXJkMIIBIjAN
# BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1H/K+BJOCnI+JluymsG4etDGqhKI
# oZdhqlGyGonAef9lb8Uz/k3X4jWwCVSfzJfiW9xOxAabzcM7QURFEi4ouNNsap/i
# Y5fKbulo+9I8HqisFaEYtSH1hs80pKwd6lTwidjn8b0EKvflK5RkEHxNwtG+dw8c
# cGf/9fPQkkJQS069322JzyoGvKO7uXcjQdhSNW4vXoDKeHvs3Pa0BOlDeZl61Srk
# NGhiQWfG4lKQ1n4s0H4a1B0jijXsafcnJD8rx6QI9WBqIZGBNBYVap3z1wlcu+WE
# Aa4fiZbmiAsSv5TGseOUu/nwtS5CB/CeVv1cXrEYzFVJxN62EV/DqlC7sQIDAQAB
# o4ICCjCCAgYwPgYJKwYBBAGCNxUHBDEwLwYnKwYBBAGCNxUIhY6ucoScvQmH0Ysk
# ham6S4KI0UiBeYO+iG+FsIsBAgFkAgEFMBMGA1UdJQQMMAoGCCsGAQUFBwMDMA4G
# A1UdDwEB/wQEAwIHgDAbBgkrBgEEAYI3FQoEDjAMMAoGCCsGAQUFBwMDMB0GA1Ud
# DgQWBBQuryp3LZezz4n5ke7AEg9cqEF1azAfBgNVHSMEGDAWgBQVPSNZ9WTCNCZL
# GW9D8POOVdwyITBIBgNVHR8EQTA/MD2gO6A5hjdodHRwOi8vcGtpLnZjdS5lZHUv
# Q2VydEVucm9sbC9WQ1UlMjBJbmZvU2VjJTIwU3ViQ0EuY3JsMHgGCCsGAQUFBwEB
# BGwwajBDBggrBgEFBQcwAoY3aHR0cDovL3BraS52Y3UuZWR1L0NlcnRFbnJvbGwv
# VkNVJTIwSW5mb1NlYyUyMFN1YkNBLmNydDAjBggrBgEFBQcwAYYXaHR0cDovL3Br
# aS52Y3UuZWR1L29jc3AwLAYDVR0RBCUwI6AhBgorBgEEAYI3FAIDoBMMEWpkbGVv
# bmFyZEB2Y3UuZWR1MFAGCSsGAQQBgjcZAgRDMEGgPwYKKwYBBAGCNxkCAaAxBC9T
# LTEtNS0yMS0zMzYyMTM0Njc0LTE0MzQyNTQ4NzAtNjE4NDI0MDE4LTE0MjExOTAN
# BgkqhkiG9w0BAQsFAAOCAQEANSoRnBOOrazC205T8RUixO7u3oOK2P8HM12r3WSs
# RPVOiIFsfNCf4yWWw3lVlmMEHv6g5QfSA/0INQgbPmhBjNlYMBKy98H9nPU4ANnl
# p3qkqvCGjLN1ZwIKelNlj5+cKMguoYqFE1gm0DXJThLPt4zAiM9H9Prvh3lyoYTe
# l767W4mgxTcEfQB1e1BewkNyFcXp962McZUMHPXSdOCBv4nCi3XBoEP1RtNguYM0
# EBv17FMUz5NA4KqH2dz913d9iFVDmCsCcgPb3QToh4BqM8M6PEXVXN0nnM9OjsTF
# C1/o/ZaT17UyjqneM4N4tJLDbIU0yip2AZvlte6weFx2mDCCBbowggOioAMCAQIC
# Ex8AAAAGzYiva2wb6vgAAAAAAAYwDQYJKoZIhvcNAQENBQAwFjEUMBIGA1UEAxML
# VkNVIFJvb3QgQ0EwHhcNMTcwOTEzMTYyNDU1WhcNMjcwOTEzMTYzNDU1WjBxMRMw
# EQYKCZImiZPyLGQBGRYDZWR1MRMwEQYKCZImiZPyLGQBGRYDdmN1MRMwEQYKCZIm
# iZPyLGQBGRYDYWRwMRQwEgYKCZImiZPyLGQBGRYEUkFNUzEaMBgGA1UEAxMRVkNV
# IEluZm9TZWMgU3ViQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDA
# c41i5s4fE5sSkmNOePH+BcAZwXebOZd1ZG7+xKG/u2hV8YAAtt1ywDobVHhoiEo5
# IabtEf9qWmW4Sd3szs3CkO592ycOBmG2Q63xMjLwoNsEor2dFL6cVL9oeZ+7Uf4v
# 23ZMRJN/42I2tTfV/1NuLOX6nZZIz1CSdYZkoTYtXqc/2nzhQyPoV4iiKcGhNSWq
# KCYYIXCpIe9NGfYU+LykOK5ogKW+zt/4jXM24/gdcJHi53nBrfxhlHVD0VtdauPw
# Jo38+79JcauogIJ6R4t57QVrts7Mt3Bgh7BA6RLwVCQqapmv82yPLHCkvjELsvMI
# +bI0Y4qEMM4uPSqmoc9zAgMBAAGjggGkMIIBoDAQBgkrBgEEAYI3FQEEAwIBADAd
# BgNVHQ4EFgQUFT0jWfVkwjQmSxlvQ/DzjlXcMiEwegYDVR0gBHMwcTBvBgcrBgEE
# AdEQMGQwOgYIKwYBBQUHAgIwLh4sAEwAZQBnAGEAbAAgAFAAbwBsAGkAYwB5ACAA
# UwB0AGEAdABlAG0AZQBuAHQwJgYIKwYBBQUHAgEWGmh0dHA6Ly9wa2kudmN1LmVk
# dS9jcHMudHh0MBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIAQwBBMAsGA1UdDwQEAwIB
# hjAPBgNVHRMBAf8EBTADAQH/MB8GA1UdIwQYMBaAFJODzUoVRHlHHgkhWGTzPLhG
# 3O9aMEIGA1UdHwQ7MDkwN6A1oDOGMWh0dHA6Ly9wa2kudmN1LmVkdS9jZXJ0ZW5y
# b2xsL1ZDVSUyMFJvb3QlMjBDQS5jcmwwUwYIKwYBBQUHAQEERzBFMEMGCCsGAQUF
# BzAChjdodHRwOi8vcGtpLnZjdS5lZHUvQ2VydEVucm9sbC9BTEJVU19WQ1UlMjBS
# b290JTIwQ0EuY3J0MA0GCSqGSIb3DQEBDQUAA4ICAQBaEiX0Yzy7dvwI0nJdYNDn
# vSmKGGlXCRHuN27hhHxk9VBO8JzdsE87WYm5fJjuH9npaPjtXzPtx5fREpUDrFVt
# qVayFEPmVtQifm0VX5S4fT4ur0rvuoILjQGRadVuXM1pYuYzyU11T2z+R899AZp6
# wXVCpS/30JDIRpjoWaXwtW1E3eoBgC1Nfxpnwdb8FPigFOHVh4ghEFg71ZxnGLGX
# z5iaQLa+LelyxaxXmLqgq/DDR5ZpuQvtQMcZT2kokEad5UCWqELYSwFP0iel6qG6
# fnL8WDpJDFC/c722efMEHE8HpFSAB/BUJb9RYwZMStExp8JG11q3xklQJxgbcT5J
# rX0Jtuc3soUDs42UjThyVCL1K1mZSL0GiLbHd6KDtsiYdV5rke1GNkJMB73Inuti
# FyHuur8AEh6TDOe5Z8pMaw6cVwGpQceb1N4Y/TTo9buloehsSBcy55rak3P7HGS1
# rs0HtU/OFpQ0SO4LvSnETtki5vp3ATIO523iYZauItVsM8CrzesxgWh5AKXfHLRl
# dJdZTQKsnGjvO0tz2cc8Uwf1MMGyXFD71kQvgQ3SksSdWh8lx7NAnt7NL8nR9T3h
# udwnaIPQQhJbjhbCHHjX/TjzEzGh2F788x9+55OFAHoLkuZg7+rKpsyNqIVWyCtX
# +HJxczOWedb2q8stnrbc1zGCEFkwghBVAgEBMIGIMHExEzARBgoJkiaJk/IsZAEZ
# FgNlZHUxEzARBgoJkiaJk/IsZAEZFgN2Y3UxEzARBgoJkiaJk/IsZAEZFgNhZHAx
# FDASBgoJkiaJk/IsZAEZFgRSQU1TMRowGAYDVQQDExFWQ1UgSW5mb1NlYyBTdWJD
# QQITdwADHyGEzSvvnOHjlQAAAAMfITAJBgUrDgMCGgUAoHgwGAYKKwYBBAGCNwIB
# DDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEE
# AYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQUdYl2bh1eZKZ8
# vCGit0tldC9pvs0wDQYJKoZIhvcNAQEBBQAEggEAcJ1zPQZ5pjInH6WpjAHEFcS4
# 6p6AX+F3nHL8kqnd1UWNxmeTiNGQzejkPb8kNjv6rLtkgxa8Uwzr2FNMcdm5vnfa
# oiJRdINh965lGoyrSGjsYzBCHMnWIM/u18JjXv3ilj09fTkQGB49o7tsqUqE0nVk
# 8vCXzS7ymixROlmNATgJ99M9KYNpft5cTV4Q0grQpj7NDHeSSdWkqwQCipE6CAWs
# XoBP1i3HqcDl181mdMhH6NiYALsax42kt/nspBJ56F1wHosfq/5hbvzImP1c4dXG
# yDxH4P39yDzPfhYStID70+QGXQ83iufqHqhNHVS//VN66/hBfbHHnMsdEgalraGC
# Diswgg4nBgorBgEEAYI3AwMBMYIOFzCCDhMGCSqGSIb3DQEHAqCCDgQwgg4AAgED
# MQ0wCwYJYIZIAWUDBAIBMIH+BgsqhkiG9w0BCRABBKCB7gSB6zCB6AIBAQYLYIZI
# AYb4RQEHFwMwITAJBgUrDgMCGgUABBTG59Ip9n4kRRMbcC8y24aFnPq25AIUR1gt
# 5gT6AgAlVCXWmZ+B/eFeVUUYDzIwMjIxMjE0MTMwNTQwWjADAgEeoIGGpIGDMIGA
# MQswCQYDVQQGEwJVUzEdMBsGA1UEChMUU3ltYW50ZWMgQ29ycG9yYXRpb24xHzAd
# BgNVBAsTFlN5bWFudGVjIFRydXN0IE5ldHdvcmsxMTAvBgNVBAMTKFN5bWFudGVj
# IFNIQTI1NiBUaW1lU3RhbXBpbmcgU2lnbmVyIC0gRzOgggqLMIIFODCCBCCgAwIB
# AgIQewWx1EloUUT3yYnSnBmdEjANBgkqhkiG9w0BAQsFADCBvTELMAkGA1UEBhMC
# VVMxFzAVBgNVBAoTDlZlcmlTaWduLCBJbmMuMR8wHQYDVQQLExZWZXJpU2lnbiBU
# cnVzdCBOZXR3b3JrMTowOAYDVQQLEzEoYykgMjAwOCBWZXJpU2lnbiwgSW5jLiAt
# IEZvciBhdXRob3JpemVkIHVzZSBvbmx5MTgwNgYDVQQDEy9WZXJpU2lnbiBVbml2
# ZXJzYWwgUm9vdCBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTAeFw0xNjAxMTIwMDAw
# MDBaFw0zMTAxMTEyMzU5NTlaMHcxCzAJBgNVBAYTAlVTMR0wGwYDVQQKExRTeW1h
# bnRlYyBDb3Jwb3JhdGlvbjEfMB0GA1UECxMWU3ltYW50ZWMgVHJ1c3QgTmV0d29y
# azEoMCYGA1UEAxMfU3ltYW50ZWMgU0hBMjU2IFRpbWVTdGFtcGluZyBDQTCCASIw
# DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALtZnVlVT52Mcl0agaLrVfOwAa08
# cawyjwVrhponADKXak3JZBRLKbvC2Sm5Luxjs+HPPwtWkPhiG37rpgfi3n9ebUA4
# 1JEG50F8eRzLy60bv9iVkfPw7mz4rZY5Ln/BJ7h4OcWEpe3tr4eOzo3HberSmLU6
# Hx45ncP0mqj0hOHE0XxxxgYptD/kgw0mw3sIPk35CrczSf/KO9T1sptL4YiZGvXA
# 6TMU1t/HgNuR7v68kldyd/TNqMz+CfWTN76ViGrF3PSxS9TO6AmRX7WEeTWKeKwZ
# Mo8jwTJBG1kOqT6xzPnWK++32OTVHW0ROpL2k8mc40juu1MO1DaXhnjFoTcCAwEA
# AaOCAXcwggFzMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEAMGYG
# A1UdIARfMF0wWwYLYIZIAYb4RQEHFwMwTDAjBggrBgEFBQcCARYXaHR0cHM6Ly9k
# LnN5bWNiLmNvbS9jcHMwJQYIKwYBBQUHAgIwGRoXaHR0cHM6Ly9kLnN5bWNiLmNv
# bS9ycGEwLgYIKwYBBQUHAQEEIjAgMB4GCCsGAQUFBzABhhJodHRwOi8vcy5zeW1j
# ZC5jb20wNgYDVR0fBC8wLTAroCmgJ4YlaHR0cDovL3Muc3ltY2IuY29tL3VuaXZl
# cnNhbC1yb290LmNybDATBgNVHSUEDDAKBggrBgEFBQcDCDAoBgNVHREEITAfpB0w
# GzEZMBcGA1UEAxMQVGltZVN0YW1wLTIwNDgtMzAdBgNVHQ4EFgQUr2PWyqNOhXLg
# p7xB8ymiOH+AdWIwHwYDVR0jBBgwFoAUtnf6aUhHn1MS1cLqBzJ2B9GXBxkwDQYJ
# KoZIhvcNAQELBQADggEBAHXqsC3VNBlcMkX+DuHUT6Z4wW/X6t3cT/OhyIGI96eP
# FeZAKa3mXfSi2VZkhHEwKt0eYRdmIFYGmBmNXXHy+Je8Cf0ckUfJ4uiNA/vMkC/W
# CmxOM+zWtJPITJBjSDlAIcTd1m6JmDy1mJfoqQa3CcmPU1dBkC/hHk1O3MoQeGxC
# bvC2xfhhXFL1TvZrjfdKer7zzf0D19n2A6gP41P3CnXsxnUuqmaFBJm3+AZX4cYO
# 9uiv2uybGB+queM6AL/OipTLAduexzi7D1Kr0eOUA2AKTaD+J20UMvw/l0Dhv5mJ
# 2+Q5FL3a5NPD6itas5VYVQR9x5rsIwONhSrS/66pYYEwggVLMIIEM6ADAgECAhB7
# 1OWvuswHP6EBIwQiQU0SMA0GCSqGSIb3DQEBCwUAMHcxCzAJBgNVBAYTAlVTMR0w
# GwYDVQQKExRTeW1hbnRlYyBDb3Jwb3JhdGlvbjEfMB0GA1UECxMWU3ltYW50ZWMg
# VHJ1c3QgTmV0d29yazEoMCYGA1UEAxMfU3ltYW50ZWMgU0hBMjU2IFRpbWVTdGFt
# cGluZyBDQTAeFw0xNzEyMjMwMDAwMDBaFw0yOTAzMjIyMzU5NTlaMIGAMQswCQYD
# VQQGEwJVUzEdMBsGA1UEChMUU3ltYW50ZWMgQ29ycG9yYXRpb24xHzAdBgNVBAsT
# FlN5bWFudGVjIFRydXN0IE5ldHdvcmsxMTAvBgNVBAMTKFN5bWFudGVjIFNIQTI1
# NiBUaW1lU3RhbXBpbmcgU2lnbmVyIC0gRzMwggEiMA0GCSqGSIb3DQEBAQUAA4IB
# DwAwggEKAoIBAQCvDoqq+Ny/aXtUF3FHCb2NPIH4dBV3Z5Cc/d5OAp5LdvblNj5l
# 1SQgbTD53R2D6T8nSjNObRaK5I1AjSKqvqcLG9IHtjy1GiQo+BtyUT3ICYgmCDr5
# +kMjdUdwDLNfW48IHXJIV2VNrwI8QPf03TI4kz/lLKbzWSPLgN4TTfkQyaoKGGxV
# YVfR8QIsxLWr8mwj0p8NDxlsrYViaf1OhcGKUjGrW9jJdFLjV2wiv1V/b8oGqz9K
# tyJ2ZezsNvKWlYEmLP27mKoBONOvJUCbCVPwKVeFWF7qhUhBIYfl3rTTJrJ7QFNY
# eY5SMQZNlANFxM48A+y3API6IsW0b+XvsIqbAgMBAAGjggHHMIIBwzAMBgNVHRMB
# Af8EAjAAMGYGA1UdIARfMF0wWwYLYIZIAYb4RQEHFwMwTDAjBggrBgEFBQcCARYX
# aHR0cHM6Ly9kLnN5bWNiLmNvbS9jcHMwJQYIKwYBBQUHAgIwGRoXaHR0cHM6Ly9k
# LnN5bWNiLmNvbS9ycGEwQAYDVR0fBDkwNzA1oDOgMYYvaHR0cDovL3RzLWNybC53
# cy5zeW1hbnRlYy5jb20vc2hhMjU2LXRzcy1jYS5jcmwwFgYDVR0lAQH/BAwwCgYI
# KwYBBQUHAwgwDgYDVR0PAQH/BAQDAgeAMHcGCCsGAQUFBwEBBGswaTAqBggrBgEF
# BQcwAYYeaHR0cDovL3RzLW9jc3Aud3Muc3ltYW50ZWMuY29tMDsGCCsGAQUFBzAC
# hi9odHRwOi8vdHMtYWlhLndzLnN5bWFudGVjLmNvbS9zaGEyNTYtdHNzLWNhLmNl
# cjAoBgNVHREEITAfpB0wGzEZMBcGA1UEAxMQVGltZVN0YW1wLTIwNDgtNjAdBgNV
# HQ4EFgQUpRMBqZ+FzBtuFh5fOzGqeTYAex0wHwYDVR0jBBgwFoAUr2PWyqNOhXLg
# p7xB8ymiOH+AdWIwDQYJKoZIhvcNAQELBQADggEBAEaer/C4ol+imUjPqCdLIc2y
# uaZycGMv41UpezlGTud+ZQZYi7xXipINCNgQujYk+gp7+zvTYr9KlBXmgtuKVG3/
# KP5nz3E/5jMJ2aJZEPQeSv5lzN7Ua+NSKXUASiulzMub6KlN97QXWZJBw7c/hub2
# wH9EPEZcF1rjpDvVaSbVIX3hgGd+Yqy3Ti4VmuWcI69bEepxqUH5DXk4qaENz7Sx
# 2j6aescixXTN30cJhsT8kSWyG5bphQjo3ep0YG5gpVZ6DchEWNzm+UgUnuW/3gC9
# d7GYFHIUJN/HESwfAD/DSxTGZxzMHgajkF9cVIs+4zNbgg/Ft4YCTnGf6WZFP3Yx
# ggJaMIICVgIBATCBizB3MQswCQYDVQQGEwJVUzEdMBsGA1UEChMUU3ltYW50ZWMg
# Q29ycG9yYXRpb24xHzAdBgNVBAsTFlN5bWFudGVjIFRydXN0IE5ldHdvcmsxKDAm
# BgNVBAMTH1N5bWFudGVjIFNIQTI1NiBUaW1lU3RhbXBpbmcgQ0ECEHvU5a+6zAc/
# oQEjBCJBTRIwCwYJYIZIAWUDBAIBoIGkMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0B
# CRABBDAcBgkqhkiG9w0BCQUxDxcNMjIxMjE0MTMwNTQwWjAvBgkqhkiG9w0BCQQx
# IgQgXvz5bJpyPaBVi18MV4z+qqk0bUXWTp59eYCCbOaOVngwNwYLKoZIhvcNAQkQ
# Ai8xKDAmMCQwIgQgxHTOdgB9AjlODaXk3nwUxoD54oIBPP72U+9dtx/fYfgwCwYJ
# KoZIhvcNAQEBBIIBAJhF3Cb1p8+Aey8IuzEs4cHmjsMkZhI8/BZzhYqy0FqFGbeZ
# 8weAuVO9U/hWG+dqKi5DLrLjQLWmKEx6sgf6m7gHQoD4IXWQ5+eiSHbPObqQmvtf
# CUiYBjnug6VPUUHp3YLWjKSRMWKTzbkDsvZkNGkkbAbJkqC/8EWil1HcB8gL0ypE
# oA9s9IHY0ul27XzhL/sVOHL9nexZr2Q9DLTjNu38LrS7ej1mlqTtl556LVX+WB8d
# E3Fi/OgJq++jZk9wkY+ZVkVPNgNEUaMjOkcdii/FKshHNRK848PacsG2mBrQ0bY7
# gJ4BW91317oO74vg04zfKSgHqwH/d5WKbANJhmo=
# SIG # End signature block
